Added appendix with DHS references and disclaimers
w3c-ccg/ldp-bbs2020 pull request #59
Opened 2021-06-01 18:03 UTC by nissimsan

Encouragement to consider if you should have your own contract numbers represented too. If so, please open issues to track for yourselves, or paste your contract numbers into the suggest changes feature of github.

2021-06-10 14:12 UTC, OR13 approved these changes

2021-06-10 14:12 UTC, OR13 requested changes
@nissimsan sorry to request changes on this, but there are a lot of white space changes... this should be contract numbers only.

2021-06-11 10:09 UTC, nissimsan commented
@OR13, noted. Is this better?

2021-06-11 13:13 UTC, OR13 approved these changes

2021-06-11 13:13 UTC, OR13 commented
@tplooker you should add your contract numbers

2021-06-11 18:53 UTC, TallTed commented on index.html
> +        70RSAT20T00000033. The content of this specification does not
As elsewhere... Keeping all contract numbers in alphanumeric order, with one number per line in the HTML source, will make it easier to see whether a number has been added.
```suggestion
        Innovation Program under contracts 
        70RSAT20T00000003, 
        and
        70RSAT20T00000033. 
        The content of this specification does not
```

2021-06-13 21:41 UTC, tplooker approved these changes

2021-06-13 21:42 UTC, tplooker commented
> @tplooker you should add your contract numbers

Yeap noted, will follow up in a subsequent PR

2021-06-13 21:42 UTC, merged